config/routes.rb
SampleApp::Application.routes.draw do 
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root :to => "pages#home"
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

  get '/help' => 'pages#help'
  get '/signup' => 'users#new'
  
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'
  
  
  
 
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)



class User < ActiveRecord::Base
  attr_accessor :password   

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, :presence  => true,
                    :format    => {:with =>email_regex },
                    :uniqueness=> {:case_sensitive =>false}
  validates :password, :presence =>true, confirmation: true, length: {within: 6..40}

  
before_save :encrypt_password 


def has_password?(submitted_password)
  encrypted_password == encrypt(submitted_password )
end

     class << self
       def authenticate(email,submitted_password)
         user = find_by_email(email)
         (user && user.has_password?(submitted_password)) ? user : nil
         
       end
       
       def authenticate_with_salt(id, cookie_salt)
         user = find_by_id(id)
         (user && user.salt === cookie_salt) ? user : nil
         
       end
     end

  private
    def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(self.password)
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
  

    
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  def about
    @title = "About"
  end
  def help
    @title = "Help"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  def create
    user = User.authenticate(params[:session][:email],
                            params[:session][:password])
                            
    if user.nil?
      flash.now[:error] ="Invalid email password/combination"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_back_or user
      
    end
  end
  
  def destroy

    sign_out 
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  
  def show
    @user= User.find(params[:id])
    @title = @user.name
  end
  def new
    @title= "Sign up"
    @user=User.new
    
  end

  def create
    @title ="Sign up"
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Zappening?"
      redirect_to @user
    else
      render 'new'
    end
 
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Zappening, what's happening around you?"
    if @title.nil?
      base_title
    else  
      "#{base_title} |#{@title}"
    end
  end
  def logo
    image_tag("Zappening.png", :class=>"round")
  end
  def d(object)
      debug object if Rails.env == "development"
    end
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    if params[:remember_me]
    cookies.permanent.signed[:remember_token] =[user.id, user.salt]
    
  else
    cookies.signed[:remember_token] =[user.id, user.salt]
    
  end
   current_user = user
  end
  
  def sign_out
    cookies.delete(:remember_token)
    current_user = nil
    
  end
  
  
  def signed_in?
    !self.current_user.nil?
  end 
#   
  def current_user=(user)
    @current_user = user
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
          redirect_to(session[:return_to] || default)
          clear_return_to
    end

    def clear_return_to
      session[:return_to] = nil
    end
  
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def remember_token
    cookies.signed[:remember_token] || [nil,nil]
  end
  
  private
  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for (user, options={ :size =>50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar profile-img',
                                            :gravatar => options)
  end
                                          
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		
		    <ul class="nav nav-pills nav-stacked"> 
		      <li> <a>
				  <i class="fa fa-lightbulb-o fa-lg"></i>
				  <%= link_to "About", about_path %>
			  </a>
			  </li>
		      <li><a>
				  <i class="fa fa-mobile-phone fa-lg"></i>
				  <%= link_to "Contact", contact_path %>
			  </a>
			  </li>
		      
		    </ul>
	</nav>
		
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="round">
		<ul class="nav nav-pills nav-stacked">
		  <li><a href="/"><i class="fa fa-home fa-fw"></i>Home</a></li>
		  <% if signed_in? %>
		  <li><a href="<%= user_path(current_user)%>"><i class="fa fa-user fa-fw"></i>Profile</a></li>
		  <% end %>
		 <% if signed_in? %>
		    <li><a href="/signout"><i class="fa fa-sign-out fa-fw"></i>Signout</a></li>
		<% else%>
		    <li><a href="/signin"><i class="fa fa-sign-in fa-fw"></i> Signin</a></li>
		 <% end %>
		  <li><a href= "/help"><i class="fa fa-exclamation fa-fw"></i> Help</a></li>
		</ul>
	
	</nav>
 
	<div class="logo">
 	<%= link_to logo, root_path%>
   	
   </div>
</header>

app/views/layouts/_stylesheets.html.erb
		  <!--[if lt IE 9]>
			<script src= "http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	      <![endif]-->
		  <%= stylesheet_link_tag 'screen', :media =>'screen'%>
		  <%= stylesheet_link_tag 'print', :media => 'print'%>
		  <!--[if lt IE 8]><%= stylesheet_link_tag 'ie' %><![endif]-->
		  <!-- <%= stylesheet_link_tag 'font', :media=> 'screen'%> -->
		  
		  <%=stylesheet_link_tag 'font-awesome', :media=>'screen'%>
		  
		  

app/views/layouts/application.html.erb
<!DOCTYPE html>
       <html>
       <head>
     	  <title><%= title %></title>
		  <%= csrf_meta_tag %>
		  <%= render 'layouts/stylesheets'%>
		  <%= favicon_link_tag 'favicon.ico' %>
		 
        </head>
		<body >
		   <div class="container">
			
		        <%=render 'layouts/header' %>
		        <section class="round">
				<% flash.each do |key, value|%>
					<div class="flash <%= key %>"> <%= value %></div>
				<% end %>
   		          <%= yield %>
		        </section>
	     <%= render 'layouts/footer'%>
		 <%= d params %>
		   
	       </div>
        </body>
  </html>

app/views/pages/about.html.erb
       <body>
		  
       <h1>about</h1>

       This is about me
       </body>
     

app/views/pages/contact.html.erb
       <body>
		
       <h1>Contacts</h1>
	   
       
       </body>
    

app/views/pages/help.html.erb
<!DOCTYPE html>
    <title>Help</title>
       <body>
		   <h1>Help</h1>
	   </body>
	   
	   
	    </html>

app/views/pages/home.html.erb
<!DOCTYPE html>
    
       <body>
		<h1>Home</h1> 
	   </body>
	   <div>
	   	<style scoped>
	   	.button-signup {
	   		color:white;
	   		background:#009900;
	   		font-size:150%;
	   		margin-left:auto;
	   		margin-right:auto;
	   		display:block;
	   		width:190px;
	   		-moz-border-radius:4px;
	   		-webkit-border-radius:4px;
	   		border-radius:4px;
	   	}
		.button-signup:hover{
			background:#00CC00;
		}
	   	</style>
		<a href="/signup">
	   	<button class="pure-button button-signup">
	   		<i class="fa fa-check fa-fw"></i>
	   		Signup
	   	</button>
		
	   </a>
	  </html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
	<%= render  'users/shared/error_messages'%>
	<div class="pure-form"> 
	<%= f.label :name %></br>
	<%= f.text_field :name, :class =>'pure-input-rounded user-form'%>
	</div>
	
	<div class="pure-form"> 
	<%= f.label :email %></br>
	<%= f.text_field :email, :class =>'pure-input-rounded user-form'%>
	</div>
	
	<div class="pure-form"> 
	<%= f.label :password %></br>
	<%= f.password_field :password, :class =>'pure-input-rounded user-form'%>
    </div>
	
	<div class="pure-form"> 
	<%= f.label :password_confirmation, "Confirmation"%></br>
	<%= f.password_field :password_confirmation, :class =>'pure-input-rounded user-form'%>
    </div>
		<div class="actions"> 
			
		<%= f.submit  "Sign up", :class =>'pure-button button-signup'%>
		
	   </div>
	
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if @user.errors.any?%>
	<div id="error_explanation">
		
		<h2>
			<%= pluralize(@user.errors.count, "error")%>
			prohibited this user from registering:
		</h2>
			<p> There were problems with the following fields</p>
			<% @user.errors.full_messages.each do |message|%>
			<ul>
				<li><%=message%></li>
			</ul>
			<%end%>
		
	</div>
<% end%>

app/views/users/show.html.erb
<h1>
<style scoped>
@font-face{
	src:url(../../fonts/HappyMonkey-Regular.ttf);
}
.profile-img{
	border-radius: 15px;	
}
.side-bar{
	text-align:center;
	border-radius:10px;
	width:30%;
	margin-bottom:-15px;
	margin-left:60%;
	text-decoration:none;
	background-color:;
	border:none;
}
#elementStyle li {
	align:center;
    padding: ;
    margin:10px;
	list-style-type:none;
	background-color:green;
	border-radius:20px;
	color: white;
	font-family:HappyMonkey-Regular;
	font-size:30px;
	
}
   
</style>


<%= gravatar_for @user %>

<%= @user.name %>
<div class="pure-table pure-table-horizontal side-bar">
   <ol id="elementStyle">
    <li><%= @user.name%></li>
    <li><%= link_to user_path(@user),user_path(@user)%></li> 
    </ol>
</div>

	

</h1>
    
	
	

app/views/welcome/index.html.erb
<!DOCTYPE html>
<h2></h2>
<p>
  The time is now: <%= Time.now %>
</p>
<div>
	<style scoped>
	.button-signup {
		color:white;
		background:#009900;
		font-size:150%;
		margin-left:auto;
		margin-right:auto;
		display:block;
		width:190px;
		-moz-border-radius:4px;
		-webkit-border-radius:4px;
		border-radius:4px;
	}
	</style>
	<button class="pure-button button-signup">
		<i class="fa fa-check fa-fw"></i>
		Signup
	</button>
	
</div>
</html>